// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.qq.tars.quickstart.client.jfgame;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface TarsRoomPrx {

	public String hello();

	public String hello(@TarsContext java.util.Map<String, String> ctx);

	public void async_hello(@TarsCallback TarsRoomPrxCallback callback);

	public void async_hello(@TarsCallback TarsRoomPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);
}
